-- Create the "projects" table
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  title text not null default '',
  description text default '',
  github_url text default '',
  live_url text default '',
  image_url text default ''
);

-- Enable Row Level Security (RLS) for the "projects" table
alter table public.projects enable row level security;


-- Create the "blog_posts" table
create table public.blog_posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  title text not null default '',
  slug text not null default '',
  body text default '',
  is_draft boolean not null default true
);

-- Add a unique constraint to the "slug" column
alter table public.blog_posts add constraint blog_posts_slug_key unique (slug);

-- Enable Row Level Security (RLS) for the "blog_posts" table
alter table public.blog_posts enable row level security;