-- 1. Drop the old tables.
-- 'CASCADE' removes any dependent objects (like policies)
DROP TABLE public.portfolio_projects CASCADE;
DROP TABLE public.blog_posts CASCADE;

-- 2. Enable the 'moddatetime' extension (if not already)
-- This will automatically update our 'updated_at' column
create extension if not exists moddatetime with schema extensions;

-- 3. Create the new unified 'content' table
create table public.content (
  id bigint generated by default as identity primary key,
  
  -- Metadata
  title text not null,
  slug text not null unique,
  description text, -- For the short summary
  image_url text, -- For a cover image
  
  -- Content
  body text, -- This is for the full MDX content
  
  -- Type & Author
  content_type text not null check (content_type in ('PROJECT', 'ARTICLE')),
  author_id uuid references public.profiles(id) on delete set null,
  
  -- Project-Specific Fields (nullable)
  github_url text,
  live_url text,
  
  -- Timestamps
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 4. Enable Row Level Security (RLS) on the new table
alter table public.content enable row level security;

-- 5. Create the trigger to auto-update 'updated_at'
create trigger handle_updated_at
before update on public.content
for each row
execute procedure extensions.moddatetime (updated_at);

-- 6. Create RLS policies for the 'content' table
-- (Same as our old policies, just adapted for the new table)

-- 6a. Allow public read-only access
create policy "Allow public read-all"
on public.content
for select
using (true);

-- 6b. Allow admin (authenticated users) full access
create policy "Allow admin full access"
on public.content
for all
using (auth.uid() is not null);